### ISSUE TITLE
Setting "apparent pole" in mount settings does not work

### ISSUE THREAD

**Issue by fdesvallees** [charleslemaire0/TeenAstro#10]
When I set "apparent" instead of "true", the mount goes into a crazy position (it goes horizontal when pointing Deneb, which is about 45 degrees altitude).

**Comment by charleslemaire0** [comment]
fixed

**Comment by EricH45** [comment]
Hi folks,

How does home position defined ?

I do excellent test last week.

before aligning I have to point a known star and sync. Then I can 
proceed aligment procedure.

all goto then point exactly the center of my CCD at F600 !!

Wonderfull!




-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
