### ISSUE TITLE
Southern Hemisphere bug - Altaz (both types) 

### ISSUE THREAD

**Issue by fdesvallees** [charleslemaire0/TeenAstro#19]
For latitude < 0, this sequence: Goto Home, Goto Coord. / N causes the mount to perform a full 360º turn instead of staying in place like it should

**Comment by fdesvallees** [comment]
Another way of detecting it: Set mount to Altaz, reboot, change display to Az / Alt. 
The displayed azimuth is 360º instead of 0º. Of course if we ask to move to North it will do the full turn.

**Comment by charleslemaire0** [comment]
Hi Francois,

I am not able to reproduce on the branch 1.4.0
Could you check it again

Charles

**Comment by fdesvallees** [comment]
Retested today with Main Unit 1.4.2, SHC 1.4.0, freshly rebuilt.  Behaviour is slightly changed, but bug is still there: After reboot with an Altaz mount in the S hemisphere, displayed coordinates are correct (Az=0, Alt=0), but requesting a Goto / Coordinates / North (or Goto / Coordinates / Alt=0, Az=0) still causes a full turn.

**Comment by charleslemaire0** [comment]
Ok thanks

**Comment by charleslemaire0** [comment]
fixed could you try?
