### ISSUE TITLE
Catalog problem

### ISSUE THREAD

**Issue by hjd1964** [charleslemaire0/TeenAstro#3]
I noticed that Stars and Messier objects with negative Declinations (all?) **have incorrect Declinations**!   Probably the Herschel catalog is that way too, I didn't sample it.

Let me know if you will tackle fixing this, if not I'll do it but I'll take me longer probably as I assume you have a ready to go method of creating the C data arrays.

**Comment by charleslemaire0** [comment]
Thanks Khalid it is now fixed
