### ISSUE TITLE
TeenAstroUploader - Space in folder name

### ISSUE THREAD

**Issue by se-o-matic** [charleslemaire0/TeenAstro#4]
I found a little bug in the TeenAstroUploader (V1.1.2)
When I start the firmware upload to the mainunit, the programm can't find the "Teensy Loader".
It's caused by a space in the folder name. I attached a screenshot from a video capture. There you can see the, that the path is cropped after the space.
Greets, Sebastian
![FehlerTeenAstroUploader](https://user-images.githubusercontent.com/16191070/55534264-2f596300-56b4-11e9-8a4e-a17ae961b042.png)

**Comment by charleslemaire0** [comment]
ok I will check that
