### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by MasterPIC** [charleslemaire0/TeenAstro#47]
Hi,

I'm not sure I properly understood the code related to meridian limit check for German equatorial mounts.

```
if (!checkMeridian(axis1, axis2, CHECKMODE_TRACKING))
    {
      if ((staA1.dir && currentSide == PIER_WEST) || (!staA2.dir && currentSide == PIER_EAST))
      {
        lastError = ERRT_MERIDIAN;
        if (movingTo)
        {
          abortSlew = true;
        }
        if (currentSide >= PIER_WEST && !forceTracking)
          sideralTracking = false;
        return;
      }
      else if (lastError == ERRT_MERIDIAN)
      {
        lastError = ERRT_NONE;
      }
    }
    else if (lastError == ERRT_MERIDIAN)
    {
      lastError = ERRT_NONE;
    }
```

Is (!staA2.dir && currentSide == PIER_EAST)) value check meant to exclude slewing to S (while the scope is on the wrong side)?
If the aim is to stop tracking for Southern Emisphere observers I think the code should be

` if ((staA1.dir && currentSide == PIER_WEST) || (!staA1.dir && currentSide == PIER_EAST))
`

**Comment by charleslemaire0** [comment]
Oh yes this is a bug introduced with the refactoring of the axis definition there is the same error with the under pole limit.

Charles
