### ISSUE TITLE
Severe axis1 limits issues

### ISSUE THREAD

**Issue by MasterPIC** [charleslemaire0/TeenAstro#70]
What are the right axis1 limits values? I'm on an equatorial mount..

By SHC axis1 min can't be less than -180deg. Lower values are rejected also by web server.
By SHC axis1 max can't be greater than 180deg. Greater values are rejected also by web server.

The controller currently is not usable. What's the latest working release?
I'm assuming your last indications related to right axis1 limits values (-270deg, 90deg) are still valid...

**Comment by charleslemaire0** [comment]
As I am using euler angle to describe the rotation the interval -270 to 90 doesn't work!
I modified the instrument coordinates for GEM to be in an interval from -180 to 180
I reported the change by mail on the group

Charles
