### ISSUE TITLE
Meridian limit not working

### ISSUE THREAD

**Issue by fdesvallees** [charleslemaire0/TeenAstro#9]
Still does not work in version 1.2 (to reproduce: set both meridian limits to zero, point to az=179 degrees, switch-on tracking. Mount should stop at 180, but keeps tracking)

**Comment by charleslemaire0** [comment]
It works as design the limit you set in the software is for goto.
For tracking there is a small buffer of +- 5 minutes.

**Comment by fdesvallees** [comment]
I just retested it, with the same result: it passes the meridian and keeps on tracking, well past 5 minutes (I left it for 15 minutes, and it was still running without errors, although both meridian limits were set to zero)

**Comment by charleslemaire0** [comment]
I can reproduce the issue, sorry

**Comment by charleslemaire0** [comment]
it should now works
